### ISSUE TITLE
Python-passlib action failing on U18

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/ansible-role-perfsonar-toolkit#4]
The change to `main.yaml` in bd2d131 causes a failure on U18:

```
TASK [ansible-role-perfsonar-toolkit : Need python-passlib to work with htpasswd module] ******************************************
fatal: [10.8.8.7]: FAILED! => {"msg": "The conditional check 'ansible_distribution is \"CentOS\" and ansible_distribution_major_version is \"7\"' failed. The error was: template error while templating string: expected token 'name', got 'string'. String: {% if ansible_distribution is \"CentOS\" and ansible_distribution_major_version is \"7\" %} True {% else %} False {% endif %}\n\nThe error appears to be in '/home/jarett/ansible-playbook-perfsonar/roles/ansible-role-perfsonar-toolkit/tasks/main.yml': line 4, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Need python-passlib to work with htpasswd module\n ^ here\n"}

PLAY RECAP ************************************************************************************************************************
10.8.8.7 : ok=28 changed=2 unreachable=0 failed=1 skipped=16 rescued=0 ignored=0
10.8.8.8 : ok=11 changed=2 unreachable=0 failed=0 skipped=1 rescued=0 ignored=0
```

**Comment by igarny** [comment]
Please note the issue with the missing “python-passlib” needed “to work with htpasswd module” is a common a requirement of Ansible for management of Linux systems.
Meaning you should be having this package on the remote host upfront. Please check the requirements section: https://github.com/perfsonar/ansible-role-perfsonar-toolkit

The simple solution is:
“apt-get install python-passlib”


Similar references can be found when looking for: Ansible This module requires the passlib Python library

**Comment by tonin** [comment]
I think the role should take care of that in a smarter way.

**Comment by igarny** [comment]
a new pull request is created with a solution for the issue

Main problem was that differentiation for the correct module is based on considerations of an indirect measure... the OS and the version...

**Comment by igarny** [comment]
Should be resolved by https://github.com/perfsonar/ansible-role-perfsonar-toolkit/commit/d92e61f514c3bd75bbc9b9cbbfe82a2120b4eb4c
